spring:
  application:
    name: micr-pay
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: localhost


server:
  port: 9000
  servlet:
    context-path: /pay

dubbo:
  registry:
    address: zookeeper://localhost:2181
  consumer:
    timeout: 6000
    retries: 0
    check: false
  scan:
    base-packages: com.bjpowernode.pay
